---
alias: Light Hall
id: c2df6567-a636-48a3-8c86-fec73b866634
description: Turn on the light in the hall when presence is detected or turn it off if there is no motion.
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.presence_hall
      - input_boolean.motion_sensor
      - alarm_control_panel.ha_alarm
      # - sensor.illuminance_hall
action:
  choose:
    # Motion detected
    - conditions:
        - condition: state
          entity_id: binary_sensor.presence_hall
          state: 'on'
        #- condition: numeric_state
        #  entity_id: sensor.illuminance_hall
        #  below: 75
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: disarmed
        - condition: state
          entity_id: input_boolean.motion_sensor
          state: 'on'
      sequence:
        - service: switch.turn_on
          entity_id: switch.circadian_lighting_hall
        - service: light.turn_on
          data:
            entity_id: light.flur
            transition: 2
          data_template:
            kelvin: >-
              {{ state_attr('sensor.circadian_values', 'colortemp') | int }}
            brightness_pct: >-
              {{ state_attr('switch.circadian_lighting_hall', 'brightness') | int }}
  # No more motion detected
  default:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_hall
    - service: light.turn_off
      data:
        entity_id: light.flur
        transition: 3