---
alias: Button Bathroom
id: 5b382c84-6d7c-459b-a39a-2b39778f296d
mode: queued
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:15:8d:00:01:87:0a:c2"
action:
  choose:
    # Single Click toggles media player in bath room.
    - conditions:
      - "{{ trigger.event.data.args.click_type == 'single' }}"
      sequence:
        - service: >
            {% if states('media_player.bath_homepod_mini') == 'on' %}
              media_player.turn_off
            {% else %}
              media_player.turn_on
            {% endif %}
          entity_id: media_player.bath_homepod_mini
    # Double Click starts the multi room radio.
    - conditions:
      - "{{ trigger.event.data.args.click_type == 'double' }}"
      sequence:
        - service: script.play_radio
          data:
            station: bremen_next (playlist)
        - service: media_player.turn_on
          entity_id: media_player.bath_homepod_mini
