---
alias: Light Storage
id: 00ddb44e-5948-4502-bc1b-749ca649b4a8
description: Turn off the light in the storage after a few minutes
mode: restart
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: light.storage
condition:
  - condition: state
    entity_id: light.storage
    state: 'on'
action:
  - delay: '00:02:30'
  - service: light.turn_off
    entity_id: light.storage
