---
homeassistant:
  name: Home

  # Localization and zone configuration
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  unit_system: metric
  time_zone: Europe/Berlin

  packages: !include_dir_named packages

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 10.0.5.0/24
        - 10.1.5.0/24
        - 10.0.10.0/24
      trusted_users:
        10.0.5.31: !secret jannis_id
        10.0.5.32: !secret jannis_id
        10.0.5.41: !secret jannis_id
        10.0.5.43: !secret jannis_id
        10.0.5.35: !secret hannah_id
        10.0.5.62: !secret hannah_id
        10.0.10.21: !secret alarmpanel_id
      allow_bypass_login: true
    - type: homeassistant

frontend:
  # HACS
  themes: !include_dir_merge_named themes

automation split: !include_dir_list automations

recorder:
  purge_keep_days: 14
  db_url: !secret recorder_db_url
  exclude: !include etc/exclude_recorder.yaml
  # Disable auto purging, I'm doing this using automations instead
  auto_purge: false

hacs:
  token: !secret github_hacs_token

# For google calendar integration
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

default_config:

ios:

http:
  server_port: !secret http_port
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.1.11
  ip_ban_enabled: true
  login_attempts_threshold: 3

# AndroidTV and media player are unavailable unless the TV is actually on.
logger:
  default: info
  logs:
    androidtv.adb_manager.adb_manager_async: critical
    aiohttp.access: critical
    aiohttp.server: critical
    homeassistant.core: error
    homeassistant.config_entries: error
    homeassistant.components.androidtv.media_player: critical
    homeassistant.components.automation: warn
    homeassistant.components.binary_sensor: error
    homeassistant.components.calendar: critical
    homeassistant.components.cert_expiry: critical
    homeassistant.components.device_tracker: error
    homeassistant.components.snmp.device_tracker: critical
    homeassistant.components.discovery: warn
    homeassistant.components.http: warn
    homeassistant.components.media_player: critical
    homeassistant.components.sensor: warn
    homeassistant.components.sensor.rest: critical
    homeassistant.components.switch: error
    homeassistant.components.rest.sensor: critical
    homeassistant.components.recorder: error
    homeassistant.components.scene: warn
    homeassistant.components.light: warn
    homeassistant.components.websocket_api: critical
    homeassistant.components.mqtt.discovery: warn
    homeassistant.components.esphome: warn
    homeassistant.components.zha: warn
    homeassistant.helpers.script: info
    homeassistant.helpers.entity: critical
    homeassistant.setup: error
    homeassistant.bootstrap: warn
    homeassistant.exceptions: info
    googleapiclient.discovery: warn
    py.warnings: error
    pyhap.hap_server: warn
    pychromecast: critical
    telegram.vendor.ptb_urllib3.urllib3.connectionpool: error
    requests.packages.urllib3.connectionpool: critical
    snapcast.control.server: warn
    urllib3.connectionpool: error
    custom_components.display: error
    custom_components.alexa_media: warn

lovelace: !include lovelace/configuration.yaml

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

browser_mod:

lovelace_gen:
  rooms: !include_dir_list lovelace/rooms

intent:
