---
title: Home
decluttering_templates: !include_dir_merge_named lovelace/decluttering_templates
views: !include_dir_merge_list lovelace/default_views
kiosk_mode:
  user_settings:
    - users:
        - "Kitchenpanel"
      kiosk: true