---
automation:
  - alias: Home Assistant Start - Notify
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    action:
      service: notify.telegram_jannis
      data:
        message: "Home Assistant started"

  - alias: Home Assistant Stop - Notify
    initial_state: true
    trigger:
      platform: homeassistant
      event: shutdown
    action:
      service: notify.telegram_jannis
      data:
        message: "Home Assistant stopped"

sensor:
  - platform: version
    name: version_current
  - platform: version
    name: version_available
    source: hassio
    image: raspberrypi4
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
