---
alias: gaming_pc_plug_pff
description: Turns off the smart plug off the gaming pc, when the pc is turned off.
id: c1664cb0-4015-44a2-a6b4-05d9b6380229
mode: queued
trigger:
  platform: state
  entity_id: switch.gaming
  from: "on"
  to: "off"
  for: "00:10:00"
action:
  service: switch.turn_off
  entity_id: switch.gaming_plug
