alias: apple_watch_vacuum
mode: parallel
id: ae93e1d4-be70-4e61-a6c5-9673da327507
description: Apple Watch Staubstauger
trigger:
  platform: event
  event_type: ios.action_fired
  event_data:
    actionName: Vacuum
action:
  - service: notify.mobile_app_iphone_von_jannis
    data:
      message: "Apple Watch: Staubsauger"
      data:
        push:
          category: vacuum
  - wait_for_trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        categoryName: vacuum
    timeout: "00:00:20"
    continue_on_timeout: false
  - variables:
      option: "{{ wait.trigger.event.data.actionName }}"
  - choose:
    - conditions: "{{ option == 'VACUUM' }}"
      sequence:
        service: vacuum.start
        entity_id: vacuum.glenn
    - conditions: "{{ option == 'MOP' }}"
      sequence:
        service: script.glenn_mop
    - conditions: "{{ option == 'STOP' }}"
      sequence:
        - service: vacuum.stop
          entity_id: vacuum.glenn
