---
display:
  - platform: fully_kiosk
    name: Küchen Tablet
    host: !secret display_fire_host
    password: !secret display_fire_password

switch:
  - platform: command_line
    switches:
      kitchen_screen:
        command_on: !secret kitchen_screen_on
        command_off: !secret kitchen_screen_off
        command_state: !secret kitchen_screen_state
        value_template: '{{ value == "on" }}'
        friendly_name: Kitchen Tablet

homeassistant:
  customize:
    sensor.32da26fb_9c72d873_battery:
      battery_alert_disabled: true
    sensor.kuchen_tablet_battery:
      battery_alert_disabled: true
