utility_meter:
  gaming_energy_daily:
    source: sensor.computer_measurement
    cycle: daily
  gaming_energy_monthly:
    source: sensor.computer_measurement
    cycle: monthly
  washing_machine_energy_daily:
    source: sensor.washing_machine_measurement
    cycle: daily
  washing_machine_energy_monthly:
    source: sensor.washing_machine_measurement
    cycle: monthly

binary_sensor:
  - platform: template
    sensors:
      washing_machine:
        friendly_name: Washing machine
        value_template: >
          {{ states("sensor.washing_machine_watts") | float(0) > 3 }}
        delay_off: "00:05:00"
        icon_template: >
          {% if is_state("binary_sensor.washing_machine", "on") %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}
