---
alias: Evening light
id: cedf6e55-5c96-465c-a091-d930adc794dd
description: Turns on the light in the living room in the evening if the tv light has been turned off.
mode: single
trigger:
  platform: state
  entity_id: media_player.android_tv
  from: 'idle'
  to: 'unavailable'
condition:
  condition: sun
  after: sunset
  after_offset: "-00:30:00"
action:
  - delay: '00:00:10'
  - service: light.turn_on
    entity_id: light.living_floor_light
