---
alias: Set Frontend Theme
id: e6c378ad-bc5d-4d75-b849-caafb206b244
description: Sets the frontend theme according to the sun level.
mode: single
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: sun.sun
  - platform: state
    entity_id: weather.openweathermap
action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: weather.openweathermap
          state: snowy
        - condition: state
          entity_id: weather.openweathermap
          state: rainy
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 3.0
      sequence:
        service: frontend.set_theme
        data:
          name: iOS Dark Mode
          mode: 'dark'
    default:
      service: frontend.set_theme
      data:
        name: iOS Light Mode
