---
alias: Shellies Announce
id: 7da8d1fb-8048-4e9c-a529-d44a50c3e642
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/1"
action:
  service: mqtt.publish
  data:
    topic: shellies/command
    payload: announce