---
alias: Speedtest
id: 6bfc5074-8144-4285-94d7-c574bc7e0819
description: Runs a speedtest
mode: single
trigger:
  platform: time_pattern
  minutes: '/5'
action:
  service: speedtestdotnet.speedtest
