---
description: Syncs the audio from spotify connect to the daapd server.
alias: Sync Spotify volume DAAPD
id: a528d04d-3583-4398-bdb6-dd7803f9822c
mode: queued
trigger:
  platform: state
  entity_id:
    - media_player.spotify_jannis
    - media_player.spotify_hannah
condition:
  - "{{ states(trigger.entity_id) == 'playing' }}"
  - "{{ state_attr(trigger.entity_id, 'source') == 'Home' }}"
  - condition: template
    value_template: >
      {% set from = trigger.from_state.attributes.volume_level | float %}
      {% set to = trigger.to_state.attributes.volume_level | float %}
      {{ to != from }}
action:
  service: media_player.volume_set
  data:
    entity_id: media_player.forked_daapd_server
    volume_level: "{{ trigger.to_state.attributes.volume_level | float }}"
