---
esphome:
  name: ${device}
  platform: ESP8266
  board: ${board}
  includes:
    - libraries/diyhueasyncudp.h
  libraries:
    - ESPAsyncUDP

status_led:
  pin:
    number: GPIO2
    inverted: True

text_sensor:
  - platform: template
    name: "light_id"
    id: light_id
    lambda: |-
      return {"esphome_diyhue_light;${mac};${name};0;0"};
    update_interval: 24h

light:
  - platform: fastled_clockless
    name: "color_led"
    id: color_led
    chipset: WS2812B
    # RX
    pin: ${pin}
    num_leds: ${num_leds}
    rgb_order: GRB

web_server:
  port: 80

custom_component:
- lambda: |-
    auto diyhue = new diyhueudp();
    return {diyhue};

switch:
  - platform: template
    name: alert
    id: alert
    optimistic: true
    turn_on_action:
      - light.turn_off: color_led
      - light.turn_on:
          id: color_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: color_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: color_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: color_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_off: color_led
      - switch.turn_off: alert
  - platform: template
    name: entertainment_switch
    id: entertainment_switch
    optimistic: true
