---
description: Vaccum clean daily
alias: vacuum_clean_daily
id: a64237e2-5c17-4022-aff6-fa8d16a19738
mode: single
trigger:
  - platform: time
    at: '10:00'
  - platform: state
    entity_id: binary_sensor.home
    to: 'off'
condition:
  condition: and
  conditions:
    - condition: time
      after: '9:00'
      before: '20:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
    - condition: state
      entity_id: group.home
      state: not_home
    - condition: state
      entity_id: input_boolean.cleaned_today
      state: 'off'
action:
  - service: vacuum.start
    entity_id: vacuum.glenn
