---
alias: Button Bedroom
id: 72c9f90d-7208-46ee-88d7-c1055f51f61a
mode: queued
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:15:8d:00:01:bc:f8:00"
action:
  choose:
    # Single Click
    - conditions:
      - "{{ trigger.event.data.args.click_type == 'single' }}"
      sequence:
        - service: light.toggle
          data:
            entity_id: light.go
            transition: 3
            kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp') | int }}"
            brightness_pct: "{{ state_attr('switch.circadian_lighting_hall', 'brightness') | int }}"
    # Double Click
    - conditions:
      - "{{ trigger.event.data.args.click_type == 'double' }}"
      sequence:
        - service: media_player.media_stop
          entity_id: media_player.bed_fernseher
