---
alias: Close the blinds
id: 41f7b145-78cd-4da8-8f94-583f478148d3
mode: single
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: CLOSE_BLINDS
action:
  # Workaround: The first call closes the cover entirely. The second call respects the position.
  - service: cover.set_cover_position
    data:
      entity_id: cover.bed
      position: 15
  - service: cover.set_cover_position
    data:
      entity_id: cover.bed
      position: 25
  