---
alias: Tablet Kitchen
id: 1f06cc38-0fea-43c3-81fc-cfec9a6662a9
description: Turn on the tablet's screen, when motion is detected
mode: restart
trigger:
  platform: state
  entity_id: binary_sensor.presence_kitchen
  to: 'on'
action:
  service: light.turn_on
  entity_id: light.kitchen_screen
