---
# Magichome RGBWW controller

esphome:
  name: led_hall
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  password: !secret esp_apipass

logger:

ota:
  password: !secret esp_otapass

output:
  - platform: esp8266_pwm
    pin: GPIO14
    id: 'color_red'
  - platform: esp8266_pwm
    pin: GPIO05
    id: 'color_green'
  - platform: esp8266_pwm
    pin: GPIO2
    id: 'color_blue'
  - platform: esp8266_pwm
    pin: GPIO12
    id: 'color_cold_white'
  - platform: esp8266_pwm
    pin: GPIO13
    id: 'color_warm_white'

light:
  - platform: rgbww
    name: Light
    red: color_red
    green: color_green
    blue: color_blue
    cold_white: color_cold_white
    warm_white: color_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
