---
substitutions:
  name: Kleiderschrank
  device: light_living_couch
  pin: D2
  num_leds: '108'
  mac: '50:02:91:78:d5:a0'

packages:
  diyhue_base: !include common/diyhue_base.yaml
  main_base: !include common/main_base.yaml
