---
substitutions:
  board: d1_mini_lite
  name: Kleiderschrank
  device: light_office_closet
  pin: GPIO2
  num_leds: '200'
  mac: 'bc:dd:c2:7a:d7:d6'

packages:
  diyhue_base: !include common/diyhue_base.yaml
  main_base: !include common/main_base.yaml
