---
substitutions:
  name: Couch
  device: light_living_couch
  pin: GPIO3
  num_leds: '108'
  # MAC TBD
  mac: '50:02:91:78:d5:a1'

packages:
  diyhue_base: !include common/diyhue_base.yaml
  main_base: !include common/main_base.yaml
